name: CI
on: 
  workflow_dispatch:
 
jobs:
 setup:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
         PC: [1, 2, 3, 4]
         Port: [10011, 10012, 10013, 10014, 10015]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup build start on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:24.04
            run: |
                echo ok
                ls -al /
                wait
                sleep 40
            shell: bash
