name: CI
on: 
  workflow_dispatch:
 
jobs:
  setup:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012, 10013, 10014, 10015]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup build start on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:24.04
            run: |
                echo ok
                ls -al /
                wait
                sleep 1m
            shell: bash

  server-rest:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012, 10013, 10014, 10015]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup build start on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:24.04
            run: |
                echo ok
                ls -al /
                wait
                sleep 1m
            shell: bash

  block-check:
    runs-on: ubuntu-22.04
    if: always()
    needs: [setup, server-rest]
    timeout-minutes: 360
    steps:
      - name: Server Clean
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:24.04
            run: |
                run: |
                echo ok
                ls -al /
                wait
                sleep 30
            shell: bash
