name: CI
on: 
  workflow_dispatch:
 
jobs:
  setup:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012, 10013, 10014, 10015]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.IMAGE }}
            run: |
                if [ ${{ matrix.Port }} == "10011" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY1 }}'
                elif [ ${{ matrix.Port }} == "10012" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY2 }}'
                elif [ ${{ matrix.Port }} == "10013" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY3 }}'
                elif [ ${{ matrix.Port }} == "10014" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY4 }}'
                else
                    C_KEY='${{ secrets.CLIENT_KEY5 }}'
                fi
                PORT=${{matrix.Port}} CLIENT_KEY=$C_KEY timeout 300m node server.js
                echo $?
            shell: bash

  server-rest:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
         Port: [10016, 10017, 10018, 10019, 10020]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port ${{matrix.Port}}
      - name: Run the Server rest process
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.IMAGE }}
            run: |
                if [ ${{ matrix.Port }} == "10016" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY6 }}'
                elif [ ${{ matrix.Port }} == "10017" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY7 }}'
                elif [ ${{ matrix.Port }} == "10018" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY8 }}'
                elif [ ${{ matrix.Port }} == "10019" ]; then
                    C_KEY='${{ secrets.CLIENT_KEY9 }}'
                else
                    C_KEY='${{ secrets.CLIENT_KEY10 }}'
                fi
                PORT=${{matrix.Port}} CLIENT_KEY=$C_KEY timeout 300m node server.js
                echo $?
            shell: bash

  block-check:
    runs-on: ubuntu-22.04
    if: always()
    needs: [setup, server-rest]
    timeout-minutes: 360
    steps:
      - name: Server Clean
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:24.04
            run: |
                run: |
                echo ok
                ls -al /
                wait
                sleep 30
            shell: bash
